<a href="https://colab.research.google.com/github/hpahama/Data_Structures/blob/main/vector_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#vector addition and scalar multiplication
print(10*np.array([1,2,3]))
print(np.array([1,2,3])+np.array([4,5,6]))
print((10*np.array([1,2,3])).tolist())

[10 20 30]
[5 7 9]
[10, 20, 30]


In [ ]:
#cosine
np.cos(3)

-0.9899924966004454

In [ ]:
#inverse cosine
import math
math.acos(.5)
#convert from radians to degrees
math.degrees(math.acos(.5))

60.00000000000001

In [ ]:
#length of a vector
np.linalg.norm([1,2,3])

3.7416573867739413

In [ ]:
#dot product of two vectors
np.dot([2,3],[4,5])

23

In [ ]:
def vector_triple(v):
  return 3*v

In [ ]:
vector_triple(np.array([2,3]))

array([6, 9])